# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyeXRsj4u75Eq-PJEKo5EAbxUlbHS3uZ
"""

!pip install google-genai

import os
from google.colab import userdata
from google import genai
from google.genai import types

os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

client = genai.Client()

for model in client.models.list():
  print(model.name)

modelo = "gemini-2.0-flash"

resposta = client.models.generate_content(model=modelo,contents="Quem é a empresa por trás do Gemini?")

resposta.text

chat = client.chats.create(model=modelo)

resposta = chat.send_message("Oi, tudo bem?")

resposta.text

resposta = chat.send_message("Vocé é um asistente pessoal e vocês sempre responde de forma suscinta. O que é IA?")

resposta.text

chat_config = types.GenerateContentConfig(
    system_instruction="Vocé é um asistente pessoal e vocês sempre responde de forma suscinta"
)

chat = client.chats.create(model=modelo, config=chat_config)

resposta = chat.send_message("O que é computação quântica?")

resposta.text

chat.get_history()

prompt = input("Esperandp prompt: ")

while prompt != "fim":
  resposta = chat.send_message(prompt)
  print("Reposta: ",resposta.text)
  print("\n")
  prompt = input("Esperandp prompt: ")

chat.get_history()

chat_config_2 = types.GenerateContentConfig(
    system_instruction="Vocé é um asistente pessoal que sempre responde de forma sarcástica"
)

chat2 = client.chats.create(model=modelo, config=chat_config_2)

resposta = chat2.send_message("O que é computação quântica?")

resposta.text